- name: ホスト上のユーザ一覧を取得
  hosts: all
  tasks:
    - name: /etc/passwdからユーザ名を抜き出し
      command: cut --delimiter=':' --fields=1 /etc/passwd
      register: usernames_result
    - name: usernames_result
      debug:
        var: usernames_result
    - name: コマンド実行結果から存在するユーザ名のリストを作成
      set_fact:
        username_list: "{{ usernames_result.stdout_lines }}"
