---
- name: MariaDB用Yumリポジトリを追加
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
- name: MariaDBサーバと関連依存パッケージのインストール
  yum:
    name: "{{ item }}"
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MariaDB-devel
    - MySQL-python
- name: MariaDBサーバ起動と自動起動の有効化
  service:
    name: mariadb
    state: started
    enabled: true
